######################################################################
# Automatically generated by qmake (2.01a) ven. 23. mai 16:31:10 2008
######################################################################
QT += widgets

# Input
HEADERS += FenCodeGenere.h FenPrincipale.h
SOURCES += FenCodeGenere.cpp main.cpp \
    fenprincipale.cpp
